# Site settings
name: Psychologue Liurno
title: Psychologue Liurno
email: celineliurno@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/psychologue-liurno"
url: "http://www.psychologue-liurno.be"

# Build settings
markdown: kramdown
permalinks: pretty


# Owner settings
address-line: Aux Houx 96, 4480 Clermont-sous-Huy
owner: Céline Liurno
head-line: Psychologue & Sexologue
phone: 0494/26.20.60